blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/chicago-aiscience/workshop-sst/discussions
    about: Ask questions and discuss ideas with the community
  - name: Code of Conduct
    url: https://github.com/chicago-aiscience/workshop-sst/blob/main/CODE_OF_CONDUCT.md
    about: Please read our Code of Conduct before participating
